import Head from "next/head";
import styles from "./layout.module.css";
import Link from "next/link";
import { ReactNode } from "react";

type DashboardLayoutProps = {
	children: ReactNode;
	home: boolean;
};

export default function Layout({ children, home }: DashboardLayoutProps) {
	return (
		<div className={styles.container}>
			<Head>
				<title>ToDo Nextjs Typescript</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>{children}</main>

			<footer className={styles.footer}>
				<p>Made by MGR</p>
			</footer>

			{!home && (
				<div className={styles.backToHome}>
					<Link href="/">
						<a>← Back to home</a>
					</Link>
				</div>
			)}
		</div>
	);
}
