import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Input from "../components/Input";

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h4 className={styles.title}>Welcome to my first Next.js ToDo app</h4>

				<Input />
			</main>

			<footer className={styles.footer}>
				<p>Made by MGR</p>
			</footer>
		</div>
	);
};

export default Home;
